src/dj_videos/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from videos.views import VideoListView as IndexView

urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('videos/', include('videos.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/videos/urls.py
from django.urls import path
from . import api
from . import views

app_name = "videos"
urlpatterns = [
    path('categories', api.get_categories, name="list-categories"),
    path('', views.VideoListView.as_view(), name="list"),
    path('<int:pk>', views.VideoDetailView.as_view(), name="detail"),
    path('create', views.VideoCreateView.as_view(), name="create"),
    path('<int:pk>/update', views.VideoUpdateView.as_view(), name="update"),
    path('<int:pk>/delete', views.VideoDeleteView.as_view(), name="delete"),
    path('<int:pk>/rate/<str:rating>', views.VideoRateView.as_view(), name="rate"),
]

src/accounts/models.py
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser
from django.db import models


USER_TYPE_CHOICES = (
    ('ADMIN', 'Administrator'),
    ('STUDENT', 'Student'), 
    ('TEACHER', 'Teacher'),
    ('PARENT', 'Parent')
)

class User(AbstractUser):
    user_type = models.CharField(_("User type"), choices=USER_TYPE_CHOICES, max_length=50)

src/videos/models.py
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.db import models
from django.core.validators import FileExtensionValidator
from django.urls import reverse

CATEGORY_TYPE_CHOICES = (
    ('ELEMENTARY', _('Elementary School')),
    ('HIGH', _('High School')),
)
CATEGORY_SUBTYPE_CHOICES = (
    ('1', _('1st year')),
    ('2', _('2nd year')),
    ('3', _('3rd year')),
    ('4', _('4th year')),
    ('5', _('5th year')),
    ('6', _('6th year')),
    ('7', _('7th year')),
    ('8', _('8th year')),
)

class Video(models.Model):
    name = models.CharField(_("Name"), max_length=512)
    description = models.TextField(_("Description"), blank=True, null=True)
    ratings = models.IntegerField(_("Ratings"), default=0)
    category_type = models.CharField(_("Scholar Seniority"), choices=CATEGORY_TYPE_CHOICES, default='ELEMENTARY', max_length=12)
    category_subtype = models.CharField(_("Class"), choices=CATEGORY_SUBTYPE_CHOICES, default='0', max_length=1)
    video = models.FileField(null=True,
                             upload_to=settings.MEDIA_ROOT,
                             validators=[
                                FileExtensionValidator(
                                    allowed_extensions=['MOV','avi','mp4','webm','mkv', 'png'])
                             ])
    
    
    created_at = models.DateTimeField(_("Created at"), auto_now=True, auto_now_add=False)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=False, auto_now_add=True)
    created_by = models.ForeignKey("accounts.User", verbose_name=_("Created by"), on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = _("Video")
        verbose_name_plural = _("Videos")
    
    def get_absolute_url(self):
        return reverse("videos:detail", kwargs={"pk": self.pk})

src/videos/forms.py
from django import forms
from .models import Video

class VideoModelForm(forms.ModelForm):
    
    class Meta:
        model = Video
        fields = ("name",
                  "description",
                  "category_type",
                  "category_subtype",
                  "video")
        widgets = {
            "name": forms.TextInput(attrs={'class': 'form-control'}),
            "description": forms.Textarea(attrs={'class': 'form-control'}),
            "category_type": forms.Select(attrs={'class': 'custom-select', 'onchange': 'toggleVideoCategories()'}),
            "category_subtype": forms.Select(attrs={'class': 'custom-select'}),
            "video": forms.FileInput(attrs={'class': 'form-control'})
        }

src/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/videos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.forms import BaseForm
from django.http.response import HttpResponse
from .models import Video
from .forms import VideoModelForm
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    FormView
)


class VideoRateView(SuccessMessageMixin, FormView):
    success_message = "Video rated successfully"
    
    def post(self, request, *args, **kwargs) -> HttpResponse:
        video = Video.objects.get(pk=kwargs['pk'])
        if kwargs['rating'] == 'plus':
            video.ratings += 1
        else:
            video.ratings -= 1
        video.save()
        
        messages.success(request, self.success_message)
        if request.GET.get('next'):
            return redirect(request.GET.get('next'))
        return redirect(video.get_absolute_url())

class VideoListView(ListView):
    model = Video

class VideoDetailView(DetailView):
    model = Video

class VideoCreateView(SuccessMessageMixin, CreateView, LoginRequiredMixin):
    model = Video
    form_class = VideoModelForm
    success_message = "Video created successfully"
    
    def form_valid(self, form: BaseForm) -> HttpResponse:
        form.instance.created_by = self.request.user
        return super(VideoCreateView, self).form_valid(form)


class VideoUpdateView(SuccessMessageMixin, UpdateView, LoginRequiredMixin):
    model = Video
    form_class = VideoModelForm
    success_message = "Video updated successfully"
    
    def form_valid(self, form: BaseForm) -> HttpResponse:
        form.instance.created_by = self.request.user
        return super(VideoUpdateView, self).form_valid(form)


class VideoDeleteView(SuccessMessageMixin, DeleteView, LoginRequiredMixin):
    model = Video
    success_message = "Video deleted successfully"
    success_url = "/videos/"

src/templates/header.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" height="20px" style="">
    <!-- Naslov -->
    <h3 class="navbar-brand h3 font-weight-bold mb-0 p-2" href="#">{{ _("Django Videos") }}</h3>
    <!-- End of Naslov -->

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-angle-down text-light"></i>
    </button>
    <!-- End of Collapse button -->

    <!-- Collapse content -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav subnav ml-auto">
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'videos:list' %}">
                    <div class="fas-icon subnav">
                        <i class="fas fa-plus-circle text-light" aria-hidden="true"></i>
                    </div>
                    <span>{{ _("Browse Videos") }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'videos:create' %}">
                    <div class="fas-icon subnav">
                        <i class="fas fa-plus-circle text-light" aria-hidden="true"></i>
                    </div>
                    <span>{{ _("Upload Video") }}</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- End of Collapse content -->
</nav>

src/templates/videos/video_card.html
<div class="card">
    <video src="{{ object.video.url }}" style="max-height: 240px" class="card-img-top w-100" controls></video>

    <div class="card-body">
        <h5 class="card-title">
            <a href="{% url "videos:detail" object.pk %}">{{ object.name }}</a>
        </h5>
        <div class="card-text">
            <span class="badge badge-primary">{{ object.get_category_type_display }}</span>
            <span class="badge badge-secondary">{{ object.get_category_subtype_display }}</span>
        </div>
    </div>
    <div class="card-footer">
        <div class="row pl-2">
            <form method="POST" class="ml-1" action="{% url "videos:rate" pk=object.pk rating="plus" %}?next={{ object.get_absolute_url }}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">
                    {% if object.ratings > 0 %}<span class="badge badge-light">{{ object.ratings }}</span>{% endif %}
                    <i class="bi bi-arrow-up"></i>
                </button>
            </form>
            <form method="POST" class="ml-1" action="{% url "videos:rate" pk=object.pk rating="minus" %}?next={{ object.get_absolute_url }}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    {% if object.ratings < 0 %}<span class="badge badge-light">{{ object.ratings }}</span>{% endif %}
                    <i class="bi bi-arrow-down"></i>
                </button>
            </form>
        </div>
    </div>
</div>

src/templates/videos/video_form.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
{% include 'messages.html' %}

<div class="container p-3">
    <div class="card m-auto border-secondary mb-3">
        <div class="card-header bg-secondary p-3">
            <h2 class="h2 text-light mb-0"><strong>{{ _("Upload Video") }}</strong></h2>
        </div>
        <div class="card-body p-5">
            <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
                {% include 'forms.html' %}
                <input type="submit" class="btn btn-primary" value={{ _("Save Video") }}>
                <a href="{% url 'videos:list' %}" class="btn btn-outline-danger">{{ _("Cancel") }}</a>
            </form>
        </div>
    </div>
</div>


{% comment %} <script src="{% static 'js/toggleCarMakes.js' %}"></script> {% endcomment %}
<script>
{% comment %} toggleActive("cars"); {% endcomment %}

{% comment %} let makes = {};
let models = {}; {% endcomment %}

fetch("/videos/categories")
    .then((categories) => categories.json())
    .then((categories) => console.log(categories));

</script>


{% endblock body %}

src/templates/videos/video_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container py-3">
    {% for object in object_list %}
    <div class="col-md-4 mb-3">
        {% include "videos/video_card.html" %}
    </div>
    {% endfor %}

</div>

{% comment %} <script>
toggleActive("cars");
</script> {% endcomment %}

{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="hr">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Videos</title>
    {% comment %} <link rel="icon" href="{% static 'images/icon.ico' %}"> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel='stylesheet' type='text/css' media='screen' href='{% static "css/style.css" %}'>
</head>
<body>
    {% include 'header.html' %}
    
    <div class="container-fluid">
        <div class="container">
            {% include 'messages.html' %}
        </div>
        {% block body %}
        {% endblock body %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>

{% comment %} <script src="{% static 'js/sidebar.js' %}"></script> {% endcomment %}

</html>

templates/forms.html
<div class="form-snippet pb-2">
    {% if form.non_field_errors %}
        <ul class="list-unstyled">
        {% for error in form.non_field_errors %}
            <li class="text-danger"><strong>{{ _("Error:") }}</strong> {{ error }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% for field in form.visible_fields %}
        <div class="form-group">
            {% if field.errors %}
            <ul class="ml-0">
            {% for error in field.errors %}
                <li class="text-danger">{{ error }}</li>
            {% endfor %}
            </ul>
            {% endif %}
            <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>
            {% if field.help_text %}
            <ul>
                <li class="help text-info">{{ field.help_text|safe }}</li>
            </ul>
            {% endif %}
            {{ field }}
        </div>
    {% endfor %}
    {% for field in form.hidden_fields %}
        <div style="display:none">{{ field }}</div>
    {% endfor %}
</div>

templates/header.html
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" height="20px" style="">
    <!-- Naslov -->
    <h3 class="navbar-brand h3 font-weight-bold mb-0 p-2" href="#">{{ _("Django Videos") }}</h3>
    <!-- End of Naslov -->

    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-angle-down text-light"></i>
    </button>
    <!-- End of Collapse button -->

    <!-- Collapse content -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav subnav ml-auto">
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'videos:list' %}">
                    <div class="fas-icon subnav">
                        <i class="fas fa-plus-circle text-light" aria-hidden="true"></i>
                    </div>
                    <span>{{ _("Browse Videos") }}</span>
                </a>
            </li>
            {% if user.is_authenticated and user.is_staff  %}
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'videos:create' %}">
                    <div class="fas-icon subnav">
                        <i class="fas fa-plus-circle text-light" aria-hidden="true"></i>
                    </div>
                    <span>{{ _("Upload Video") }}</span>
                </a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link d-flex" href="{% url 'admin:logout' %}">
                    <div class="fas-icon subnav">
                        <i class="fas fa-plus-circle text-light" aria-hidden="true"></i>
                    </div>
                    <span>{{ _("Logout") }}</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
    <!-- End of Collapse content -->
</nav>

templates/messages.html
{% if messages %}
<div id="messages" class="mt-2">
    <div class="row m-0">
        <div class="col-md-12 bg-{{ message.tags }} p-0">
        {% for message in messages %}
            {% if message.tags == "success" %}
            <div class="alert d-flex alert-dismissible alert-{{ message.tags }} p-3 mb-0">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <div class="fas-icon">
                    <i class="fas fa-check-circle fa-lg"></i> 
                </div>
                <p class="pl-2 mb-0">{{ message }}</p>
            </div>
            {% elif message.tags == "warning" %}
            <div class="alert d-flex alert-dismissible alert-{{ message.tags }} p-3 mb-0">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <div class="fas-icon">
                    <i class="fas fa-exclamation-circle fa-lg"></i> 
                </div>
                <p class="pl-2 mb-0">{{ message }}</p>
            </div>
            {% elif message.tags == "danger" %}
            <div class="alert d-flex alert-dismissible alert-{{ message.tags }} p-3 mb-0">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <div class="fas-icon">
                    <i class="fas fa-times-circle fa-lg"></i> 
                </div>
                <p class="pl-2 mb-0">{{ message }}</p>
            </div>
            {% endif %}
        {% endfor %}
        </div>
    </div>
</div>
{% endif %}

templates/videos/video_card.html
<div class="card">
    <video src="{{ object.video.url }}" style="max-height: 200px" class="card-img-top w-100" controls></video>

    <div class="card-body">
        <h5 class="card-title">
            <a href="{% url "videos:detail" object.pk %}">{{ object.name }}</a>
        </h5>
        <div class="card-text">
            <span class="badge badge-primary">{{ object.get_category_type_display }}</span>
            <span class="badge badge-secondary">{{ object.get_category_subtype_display }}</span>
        </div>
    </div>
    <div class="card-footer">
        <div class="row pl-2">
            <form method="POST" class="ml-1" action="{% url "videos:rate" pk=object.pk rating="plus" %}?next=/videos">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">
                    {% if object.ratings > 0 %}<span class="badge badge-light">{{ object.ratings }}</span>{% endif %}
                    <i class="bi bi-arrow-up"></i>
                </button>
            </form>
            <form method="POST" class="ml-1" action="{% url "videos:rate" pk=object.pk rating="minus" %}?next=/videos">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">
                    {% if object.ratings < 0 %}<span class="badge badge-light">{{ object.ratings }}</span>{% endif %}
                    <i class="bi bi-arrow-down"></i>
                </button>
            </form>
        </div>
    </div>
</div>

templates/videos/video_confirm_delete.html
{% extends "base.html" %}

{% block body %}

<div class="container">
    <div class="row mt-3">
        <div class="col-md-12 text-center mb-3">
            <form method="POST">{% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        <fieldset class="form-group">
                            <h2>{{ _("Are you sure you want to delete video this video?") }}</h2>
                            <div class="card m-auto" style="max-width: 720px">
                                <div class="card-header p-0">
                                    <video max-height="420px" width="100%" controls>
                                        <source src="{{ object.video.url }}" type="video/mp4">
                                    </video>
                                </div>
                                <div class="card-body h-100 mb-2">
                                    <h4 class="card-title">{{ object.name }}</h4>
                                    <p class="card-subtitle">
                                        <i class="fas fa-address-card"></i>
                                        <span>{{ object.ratings }}</span>
                                    </p>
                                </div>
                            </div>
                        </fieldset>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">{{ _("Yes") }}</button>
                            <a href="{% url 'videos:list' %}" class="btn btn-danger">{{ _("No") }}</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% load static %}

{% comment %} <script type="module">
import { makeActive } from '{% static 'js/sidenavItemActive.js' %}';

window.onload = makeActive('departmentsSidenav', false, false);
</script> {% endcomment %}


{% endblock body %}

templates/videos/video_detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row align-items-center mt-4">
        <div class="col-lg-12">
            <div class="card">
                <video src="{{ object.video.url }}" style="max-height: 480px" class="card-img-top w-100" controls></video>

                <div class="card-body">
                    <h5 class="card-title">{{ object.name }}</h5>
                    <p class="card-subtitle mb-2 text-muted">{{ _("Created at ") }}{{ object.created_at }}</p>
                    <div class="card-text">
                        <span class="badge badge-primary">{{ object.get_category_type_display }}</span>
                        <span class="badge badge-secondary">{{ object.get_category_subtype_display }}</span>
                    </div>
                    <p class="card-text">{{ object.description }}</p>
                </div>
                <div class="card-footer">
                    <div class="row pl-2">
                        <div class="col d-flex">
                            <form method="POST" class="ml-1" action="{% url "videos:rate" pk=object.pk rating="plus" %}?next={{ object.get_absolute_url }}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">
                                    {% if object.ratings > 0 %}<span class="badge badge-light">{{ object.ratings }}</span>{% endif %}
                                    <i class="bi bi-arrow-up"></i>
                                </button>
                            </form>
                            <form method="POST" class="ml-1" action="{% url "videos:rate" pk=object.pk rating="minus" %}?next={{ object.get_absolute_url }}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    {% if object.ratings < 0 %}<span class="badge badge-light">{{ object.ratings }}</span>{% endif %}
                                    <i class="bi bi-arrow-down"></i>
                                </button>
                            </form>
                        </div>
                        <div class="col text-right">
                            <a href="{% url "videos:update" object.pk %}" class="btn btn-primary">
                                <i class="bi bi-pen"></i>
                                <span>{{ _("Edit") }}</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

templates/videos/video_form.html
{% extends 'base.html' %}

{% load static %}

{% block body %}
{% include 'messages.html' %}

<div class="container p-3">
    <div class="card m-auto border-secondary mb-3">
        <div class="card-header bg-secondary p-3">
            <h2 class="h2 text-light mb-0"><strong>{{ _("Upload Video") }}</strong></h2>
        </div>
        <div class="card-body p-5">
            <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
                {% include 'forms.html' %}
                <input type="submit" class="btn btn-primary" value={{ _("Save Video") }}>
                <a href="{% url 'videos:list' %}" class="btn btn-outline-danger">{{ _("Cancel") }}</a>
            </form>
        </div>
    </div>
</div>


<script src="{% static 'js/toggleVideoCategories.js' %}">
    toggleVideoCategories()
</script>
<script>
{% comment %} toggleActive("cars"); {% endcomment %}

{% comment %} let makes = {};
let models = {}; {% endcomment %}


</script>


{% endblock body %}

templates/videos/video_list.html
{% extends 'base.html' %}

{% block body %}

<div class="container py-3">
    <div class="row">
        {% for object in object_list %}
        <div class="col-lg-4 mb-3">
            {% include "videos/video_card.html" %}
        </div>
        {% endfor %}
    </div>
</div>

{% comment %} <script>
toggleActive("cars");
</script> {% endcomment %}

{% endblock body %}